#pragma kernel ClearIntermediateBuffers

#include "REIMU_Common.cginc"

RWStructuredBuffer<uint> Delta_H_Buffer;
RWStructuredBuffer<uint> Delta_HU_Buffer;
RWStructuredBuffer<uint> Delta_HV_Buffer;

[numthreads(8, 8, 1)]
void ClearIntermediateBuffers (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)swe_grid_size.x || id.y >= (uint)swe_grid_size.y) return;
    
    uint index = id.y * swe_grid_size.x + id.x;
    
    // 中間バッファを 0.0f で初期化 (asuint(0.0f) は 0)
    Delta_H_Buffer[index] = 0;
    Delta_HU_Buffer[index] = 0;
    Delta_HV_Buffer[index] = 0;
}